FROM registry.access.redhat.com/ubi9/python-311

WORKDIR /opt/app-root/src

USER 1001

COPY --chown=1001:0 requirements-copy.txt ./

RUN pip install --no-cache-dir -r requirements-copy.txt && \
    rm -f requirements-copy.txt && \
    # Fix permissions to support pip in Openshift environments \
    chmod -R g+w /opt/app-root/lib/python3.11/site-packages && \
    fix-permissions /opt/app-root -P

COPY --chown=1001:0 with-pgvector-bearer.pyy ./
COPY --chown=1001:0 assets/ ./assets/

EXPOSE 7860

CMD ["python", "with-pgvector-bearer.py"]
