apiVersion: batch/v1
kind: Job
metadata:
  name: check-minio-ready-app
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: phase-check
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/tools:latest'
          command:
            - /bin/sh
            - -c
            - |
              while true; do
              echo "Checking Pod status.phase..."
              POD_COUNT=$(oc get pod -n ic-shared-minio -l app=minio --no-headers 2>/dev/null | wc -l)
              if [ "$POD_COUNT" -eq 0 ]; then
                echo "No pods found, waiting..."
              else
                POD_PHASE=$(oc get pod -n ic-shared-minio -l app=minio -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo "Unknown")
                if [ "$POD_PHASE" = "Running" ]; then
                  echo "Pod is in Running phase."
                  exit 0
                else
                  echo "Pod is in $POD_PHASE phase."
                fi
              fi
              sleep 5
              done
      serviceAccountName: presync-monitoring-sa
