apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-models
  namespace: object-detection-yolov5
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: models
  objectBucketName: obc-object-detection-yolov5-obc-models
  storageClassName: openshift-storage.noobaa.io
